<a href="https://colab.research.google.com/github/sruthi-veeramaneni/2303A51308_PNS/blob/main/lab_1(pns).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([[9,10,11],[15,16,17],[21,22,23],[35,36,37]])
print(A)


[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [35 36 37]]


In [ ]:
print(A[:,2])

[11 17 23 37]


In [ ]:
print(A[2,:])

[21 22 23]


In [ ]:
print(np.size(A))

12


In [ ]:
print(A[2,2])

23
